# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progression.ui'
#
# Created: Wed Jan  7 14:08:14 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_progressionDialog(object):
    def setupUi(self, progressionDialog):
        progressionDialog.setObjectName("progressionDialog")
        progressionDialog.resize(409, 431)
        self.buttonBox = QtGui.QDialogButtonBox(progressionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtGui.QGroupBox(progressionDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 381, 61))
        self.groupBox.setObjectName("groupBox")
        self.addchord = QtGui.QPushButton(self.groupBox)
        self.addchord.setGeometry(QtCore.QRect(300, 20, 71, 27))
        self.addchord.setObjectName("addchord")
        self.bars = QtGui.QComboBox(self.groupBox)
        self.bars.setGeometry(QtCore.QRect(240, 20, 51, 22))
        self.bars.setObjectName("bars")
        self.romannumeral = QtGui.QComboBox(self.groupBox)
        self.romannumeral.setGeometry(QtCore.QRect(70, 20, 51, 22))
        self.romannumeral.setObjectName("romannumeral")
        self.chordsuffix = QtGui.QComboBox(self.groupBox)
        self.chordsuffix.setGeometry(QtCore.QRect(130, 20, 61, 22))
        self.chordsuffix.setObjectName("chordsuffix")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 41, 17))
        self.label_2.setObjectName("label_2")
        self.accidentals = QtGui.QComboBox(self.groupBox)
        self.accidentals.setGeometry(QtCore.QRect(10, 20, 51, 22))
        self.accidentals.setObjectName("accidentals")
        self.groupBox_2 = QtGui.QGroupBox(progressionDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 381, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.repeat = QtGui.QSpinBox(self.groupBox_2)
        self.repeat.setGeometry(QtCore.QRect(300, 40, 54, 23))
        self.repeat.setObjectName("repeat")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(300, 20, 56, 17))
        self.label_3.setObjectName("label_3")
        self.progression = QtGui.QListWidget(self.groupBox_2)
        self.progression.setGeometry(QtCore.QRect(10, 20, 281, 91))
        self.progression.setObjectName("progression")
        self.addprogression = QtGui.QPushButton(self.groupBox_2)
        self.addprogression.setGeometry(QtCore.QRect(300, 80, 71, 27))
        self.addprogression.setObjectName("addprogression")
        self.groupBox_3 = QtGui.QGroupBox(progressionDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 381, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressionsequence = QtGui.QListWidget(self.groupBox_3)
        self.progressionsequence.setGeometry(QtCore.QRect(10, 60, 351, 91))
        self.progressionsequence.setObjectName("progressionsequence")
        self.progressionname = QtGui.QLineEdit(self.groupBox_3)
        self.progressionname.setGeometry(QtCore.QRect(90, 30, 271, 23))
        self.progressionname.setObjectName("progressionname")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 30, 56, 17))
        self.label.setObjectName("label")

        self.retranslateUi(progressionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), progressionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), progressionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(progressionDialog)

    def retranslateUi(self, progressionDialog):
        progressionDialog.setWindowTitle(QtGui.QApplication.translate("progressionDialog", "Edit Progression", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("progressionDialog", "Chord", None, QtGui.QApplication.UnicodeUTF8))
        self.addchord.setToolTip(QtGui.QApplication.translate("progressionDialog", "Add chord to progression", None, QtGui.QApplication.UnicodeUTF8))
        self.addchord.setText(QtGui.QApplication.translate("progressionDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.bars.setToolTip(QtGui.QApplication.translate("progressionDialog", "Number of bars this progression should last", None, QtGui.QApplication.UnicodeUTF8))
        self.romannumeral.setToolTip(QtGui.QApplication.translate("progressionDialog", "Note to build chord on", None, QtGui.QApplication.UnicodeUTF8))
        self.chordsuffix.setToolTip(QtGui.QApplication.translate("progressionDialog", "Chord suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("progressionDialog", "Number of bars this progression should last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("progressionDialog", "Bars:", None, QtGui.QApplication.UnicodeUTF8))
        self.accidentals.setToolTip(QtGui.QApplication.translate("progressionDialog", "Accidentals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("progressionDialog", "Progression", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("progressionDialog", "Repeat:", None, QtGui.QApplication.UnicodeUTF8))
        self.progression.setToolTip(QtGui.QApplication.translate("progressionDialog", "Progression", None, QtGui.QApplication.UnicodeUTF8))
        self.addprogression.setToolTip(QtGui.QApplication.translate("progressionDialog", "Add progression to sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.addprogression.setText(QtGui.QApplication.translate("progressionDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("progressionDialog", "Progression sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.progressionsequence.setToolTip(QtGui.QApplication.translate("progressionDialog", "Progression sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.progressionname.setToolTip(QtGui.QApplication.translate("progressionDialog", "Name of the progression sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("progressionDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))

