from registry import GetValue
from registry import SetValue
from registry import DeleteValue
from registry import CreateKey
from registry import DeleteKey
from registry import DeleteTree
from registry import QueryInfoKey
from registry import GetKeyValues
from registry import GetSubKeys
from registry import GetDump
from registry import GetValues
from registry import GetKeysModifiedAfter
