function v = isvelocityname(prop)

velnames = {'dtheta','du_ctr','dv_ctr','du_cor','dv_cor','velmag_ctr','velmag',...
  'absdv_cor','flipdv_cor','absdtheta','smoothdtheta','abssmoothdtheta','du_tail',...
  'dv_tail','absdu_tail','absdv_tail','ddist2wall','absdangle2wall',...
  'magveldiff_center','magveldiff_nose2ell','magveldiff_ell2nose','magveldiff_anglesub',...
  'veltoward_center','veltoward_nose2ell','veltoward_ell2nose','veltoward_anglesub',...
  'dcenter','ddnose2ell','ddell2nose','danglesub'};
v = ismember(prop,velnames);