# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'improviser/qtGUI/improviser.ui'
#
# Created: Tue Jan  6 09:48:48 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 436)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtGui.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 10, 571, 341))
        self.Tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.Tabs.setElideMode(QtCore.Qt.ElideLeft)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 521, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 111, 17))
        self.label_3.setObjectName("label_3")
        self.bpm = QtGui.QSpinBox(self.groupBox)
        self.bpm.setGeometry(QtCore.QRect(150, 30, 111, 23))
        self.bpm.setMinimum(1)
        self.bpm.setMaximum(1000)
        self.bpm.setProperty("value", QtCore.QVariant(120))
        self.bpm.setObjectName("bpm")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 17))
        self.label.setObjectName("label")
        self.wildness = QtGui.QDoubleSpinBox(self.groupBox)
        self.wildness.setGeometry(QtCore.QRect(150, 70, 111, 23))
        self.wildness.setDecimals(5)
        self.wildness.setMaximum(100.0)
        self.wildness.setSingleStep(0.025)
        self.wildness.setProperty("value", QtCore.QVariant(0.5))
        self.wildness.setObjectName("wildness")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 111, 17))
        self.label_2.setObjectName("label_2")
        self.swing = QtGui.QCheckBox(self.groupBox)
        self.swing.setGeometry(QtCore.QRect(30, 100, 83, 22))
        self.swing.setObjectName("swing")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(270, 70, 101, 17))
        self.label_6.setObjectName("label_6")
        self.resolution = QtGui.QComboBox(self.groupBox)
        self.resolution.setGeometry(QtCore.QRect(390, 30, 111, 22))
        self.resolution.setObjectName("resolution")
        self.key = QtGui.QComboBox(self.groupBox)
        self.key.setGeometry(QtCore.QRect(390, 70, 111, 22))
        self.key.setObjectName("key")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.label_4.setObjectName("label_4")
        self.projectname = QtGui.QLineEdit(self.tab)
        self.projectname.setGeometry(QtCore.QRect(140, 20, 151, 23))
        self.projectname.setObjectName("projectname")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(310, 20, 56, 17))
        self.label_5.setObjectName("label_5")
        self.loop = QtGui.QSpinBox(self.tab)
        self.loop.setGeometry(QtCore.QRect(420, 20, 111, 23))
        self.loop.setMaximum(10000)
        self.loop.setProperty("value", QtCore.QVariant(1))
        self.loop.setObjectName("loop")
        self.duration = QtGui.QSpinBox(self.tab)
        self.duration.setGeometry(QtCore.QRect(410, 100, 111, 23))
        self.duration.setMinimum(1)
        self.duration.setMaximum(1000)
        self.duration.setProperty("value", QtCore.QVariant(1))
        self.duration.setObjectName("duration")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(310, 100, 56, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 81, 17))
        self.label_8.setObjectName("label_8")
        self.movement = QtGui.QComboBox(self.tab)
        self.movement.setGeometry(QtCore.QRect(140, 100, 151, 22))
        self.movement.setObjectName("movement")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 81, 17))
        self.label_9.setObjectName("label_9")
        self.soundfont = QtGui.QLineEdit(self.tab)
        self.soundfont.setGeometry(QtCore.QRect(140, 60, 391, 23))
        self.soundfont.setObjectName("soundfont")
        self.Tabs.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.addblockbutton = QtGui.QPushButton(self.tab_3)
        self.addblockbutton.setGeometry(QtCore.QRect(470, 10, 80, 27))
        self.addblockbutton.setObjectName("addblockbutton")
        self.removeblock = QtGui.QPushButton(self.tab_3)
        self.removeblock.setEnabled(True)
        self.removeblock.setGeometry(QtCore.QRect(470, 50, 80, 27))
        self.removeblock.setObjectName("removeblock")
        self.pushButton_5 = QtGui.QPushButton(self.tab_3)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(470, 90, 80, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.blockcombo = QtGui.QComboBox(self.tab_3)
        self.blockcombo.setGeometry(QtCore.QRect(10, 10, 451, 22))
        self.blockcombo.setObjectName("blockcombo")
        self.blocks = QtGui.QListWidget(self.tab_3)
        self.blocks.setGeometry(QtCore.QRect(10, 40, 451, 251))
        self.blocks.setObjectName("blocks")
        self.Tabs.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.addinstrumentbutton = QtGui.QPushButton(self.tab_2)
        self.addinstrumentbutton.setGeometry(QtCore.QRect(470, 10, 80, 27))
        self.addinstrumentbutton.setObjectName("addinstrumentbutton")
        self.pushButton_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 90, 80, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.removeinstrument = QtGui.QPushButton(self.tab_2)
        self.removeinstrument.setEnabled(True)
        self.removeinstrument.setGeometry(QtCore.QRect(470, 50, 80, 27))
        self.removeinstrument.setObjectName("removeinstrument")
        self.instrumentcombo = QtGui.QComboBox(self.tab_2)
        self.instrumentcombo.setGeometry(QtCore.QRect(10, 10, 451, 22))
        self.instrumentcombo.setObjectName("instrumentcombo")
        self.pushButton_12 = QtGui.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(470, 270, 80, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.instruments = QtGui.QListWidget(self.tab_2)
        self.instruments.setGeometry(QtCore.QRect(10, 40, 451, 261))
        self.instruments.setObjectName("instruments")
        self.Tabs.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.addprogressionbutton = QtGui.QPushButton(self.tab_4)
        self.addprogressionbutton.setGeometry(QtCore.QRect(470, 10, 80, 27))
        self.addprogressionbutton.setObjectName("addprogressionbutton")
        self.pushButton_10 = QtGui.QPushButton(self.tab_4)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(470, 90, 80, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.removeprogression = QtGui.QPushButton(self.tab_4)
        self.removeprogression.setEnabled(True)
        self.removeprogression.setGeometry(QtCore.QRect(470, 50, 80, 27))
        self.removeprogression.setObjectName("removeprogression")
        self.progressioncombo = QtGui.QComboBox(self.tab_4)
        self.progressioncombo.setGeometry(QtCore.QRect(10, 10, 451, 22))
        self.progressioncombo.setObjectName("progressioncombo")
        self.pushButton_13 = QtGui.QPushButton(self.tab_4)
        self.pushButton_13.setGeometry(QtCore.QRect(470, 270, 80, 27))
        self.pushButton_13.setObjectName("pushButton_13")
        self.progressions = QtGui.QListWidget(self.tab_4)
        self.progressions.setGeometry(QtCore.QRect(10, 40, 451, 261))
        self.progressions.setObjectName("progressions")
        self.Tabs.addTab(self.tab_4, "")
        self.startbutton = QtGui.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(300, 360, 80, 27))
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtGui.QPushButton(self.centralwidget)
        self.stopbutton.setEnabled(False)
        self.stopbutton.setGeometry(QtCore.QRect(400, 360, 80, 27))
        self.stopbutton.setObjectName("stopbutton")
        self.no_fluidsynth = QtGui.QCheckBox(self.centralwidget)
        self.no_fluidsynth.setGeometry(QtCore.QRect(210, 360, 83, 22))
        self.no_fluidsynth.setObjectName("no_fluidsynth")
        self.uploadbutton = QtGui.QPushButton(self.centralwidget)
        self.uploadbutton.setEnabled(False)
        self.uploadbutton.setGeometry(QtCore.QRect(500, 360, 80, 27))
        self.uploadbutton.setObjectName("uploadbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setMenuRole(QtGui.QAction.ApplicationSpecificRole)
        self.action_Load.setObjectName("action_Load")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionS_ave_as = QtGui.QAction(MainWindow)
        self.actionS_ave_as.setObjectName("actionS_ave_as")
        self.menu_File.addAction(self.action_Load)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionS_ave_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionE_xit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "qtImproviser - Untitled.imp", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Default settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Default resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Default BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Default wildness", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setStatusTip(QtGui.QApplication.translate("MainWindow", "Swing the notes", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setText(QtGui.QApplication.translate("MainWindow", "Swing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Default key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Project name", None, QtGui.QApplication.UnicodeUTF8))
        self.projectname.setText(QtGui.QApplication.translate("MainWindow", "Untitled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many times the movement should be looped", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.loop.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many times the movement should be looped", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many times a block should be played", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setStatusTip(QtGui.QApplication.translate("MainWindow", "The movement dictates the order of the blocks, progressions and instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Movement", None, QtGui.QApplication.UnicodeUTF8))
        self.movement.setStatusTip(QtGui.QApplication.translate("MainWindow", "The movement dictates the order of the blocks, progressions and instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setStatusTip(QtGui.QApplication.translate("MainWindow", "The location of the soundfont to use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Soundfont", None, QtGui.QApplication.UnicodeUTF8))
        self.soundfont.setStatusTip(QtGui.QApplication.translate("MainWindow", "The location of the soundfont to use", None, QtGui.QApplication.UnicodeUTF8))
        self.soundfont.setText(QtGui.QApplication.translate("MainWindow", "default.sf2", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.addblockbutton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.removeblock.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.addinstrumentbutton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.removeinstrument.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.addprogressionbutton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.removeprogression.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Progressions", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start generating music", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Stop generating music", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.no_fluidsynth.setStatusTip(QtGui.QApplication.translate("MainWindow", "Disable audio output. Only write midi file.", None, QtGui.QApplication.UnicodeUTF8))
        self.no_fluidsynth.setText(QtGui.QApplication.translate("MainWindow", "No audio", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadbutton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Upload midi to the Improviser homepage", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadbutton.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setToolTip(QtGui.QApplication.translate("MainWindow", "Load a previously saved project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setStatusTip(QtGui.QApplication.translate("MainWindow", "Load a previously saved project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionS_ave_as.setText(QtGui.QApplication.translate("MainWindow", "S&ave as", None, QtGui.QApplication.UnicodeUTF8))

