version = "0.4"
author = "Patrick Lewis"
email = "plewis@spamcop.net"
copyright = "Copyright 2008 Patrick Lewis"
license = "MIT"
summary = "A set of TurboGears templates to provide user registration functions."
home_page = "http://patrickhlewis.googlepages.com/registration.html"