#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'tasks-tracker',
 'build_date': '2010-03-11 03:38:36 +0000',
 'clean': None,
 'date': '2010-03-11 03:32:56 +0000',
 'revision_id': 'mohdiarra@gmail.com-20100311033256-lnqcul053vn6mivd',
 'revno': 71}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
