
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'LALR'

_lr_signature = 'b\x0b\x00\xeeh\x16\xf7\xd4q\\\x0e\xf8__\xc2K'

_lr_action_items = {'DIGITS':([4,],[6,]),'$end':([0,1,2,3,4,5,6,],[-1,-2,0,-3,-6,-4,-5,]),'ATOM':([0,1,3,4,5,6,],[4,4,-3,-6,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _lr_action.has_key(_x):  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,],[1,]),'mw':([0,],[2,]),'species':([0,1,],[3,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _lr_goto.has_key(_x): _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('mw',0,'p_mw_empty','c:\\lang\\Python25\\Lib\\site-packages\\EasyExtend\\trail\\ply_mw.py',92),
  ('mw',1,'p_mw_formula','c:\\lang\\Python25\\Lib\\site-packages\\EasyExtend\\trail\\ply_mw.py',96),
  ('formula',1,'p_first_species_term','c:\\lang\\Python25\\Lib\\site-packages\\EasyExtend\\trail\\ply_mw.py',101),
  ('formula',2,'p_species_list','c:\\lang\\Python25\\Lib\\site-packages\\EasyExtend\\trail\\ply_mw.py',105),
  ('species',2,'p_species','c:\\lang\\Python25\\Lib\\site-packages\\EasyExtend\\trail\\ply_mw.py',109),
  ('species',1,'p_species_default','c:\\lang\\Python25\\Lib\\site-packages\\EasyExtend\\trail\\ply_mw.py',113),
]
