SERVICE_LOGIN = 0x01
SERVICE_LOGOUT = 0x02
SERVICE_ISAWAY = 0x03
SERVICE_ISBACK = 0x04
SERVICE_IDLE = 0x05
SERVICE_MESSAGE = 0x06
SERVICE_NEWCONTACT = 0x0F

SERVICE_ADDBUDDY = 0x83
SERVICE_REMBUDDY = 0x84
SERVICE_IGNOREBUDDY = 0x85
SERVICE_DENYBUDDY = 0x86

SERVICE_ADDBUDDYVALIDATE = 0x8A
SERVICE_BUDDYREQ = 0xD6
SERVICE_AUTH = 0x57
SERVICE_AUTHRESP = 0x54
SERVICE_HANDSHAKE = 0x4C
SERVICE_LIST = 0x55
SERVICE_PING = 0x12
SERVICE_STATUS = 0xC6
SERVICE_NOTIFY = 0x4B

        
LOGIN_OK = '0'
LOGIN_UNAME = '3'
LOGIN_PASSWD = '13'
LOGIN_LOCK = '14'
LOGIN_DUPL = '42'

status = {
    0:"STATUS_AVAILABLE",
    1:"STATUS_BRB",
    2:"STATUS_BUSY",
    3:"STATUS_NOTATHOME",
    4:"STATUS_NOTATDESK",
    5:"STATUS_NOTINOFFICE",
    6:"STATUS_ONPHONE",
    7:"STATUS_ONVACATION",
    8:"STATUS_OUTTOLUNCH",
    9:"STATUS_STEPPEDOUT",
    12:"STATUS_INVISIBLE",
    99:"STATUS_CUSTOM",
    999:"STATUS_IDLE",
    -1:"STATUS_OFFLINE",
    "AVAILABLE":'0',
    "BRB":'1',
    "BUSY":'2',
    "NOTATHOME":'3',
    "NOTATDESK":'4',
    "NOTINOFFICE":'5',
    "ONPHONE":'6',
    "ONVACATION":'7',
    "OUTTOLUNCH":'8',
    "STEPPEDOUT":'9',
    "INVISIBLE":'12',
    "CUSTOM":'99',
    "IDLE":'999',
}
    