#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Sat Aug 18 14:29:40 2007

import wx
import events

class NewGameBasePanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NewGameBasePanel.__init__
        kwds["style"] = wx.STATIC_BORDER|wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.static_line_1 = wx.StaticLine(self, -1)
        self.gameDescriptionLabel = wx.StaticText(self, -1, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        
    def __set_properties(self):
        # begin wxGlade: NewGameBasePanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NewGameBasePanel.__do_layout
        newGameSizer = wx.BoxSizer(wx.VERTICAL)
        newGameSizer.Add(self.static_line_1, 0, wx.EXPAND, 0)
        newGameSizer.Add(self.gameDescriptionLabel, 0, wx.ALL|wx.EXPAND, 2)
        self.SetAutoLayout(True)
        self.SetSizer(newGameSizer)
        newGameSizer.Fit(self)
        newGameSizer.SetSizeHints(self)
        # end wxGlade
        
# end of class NewGameBasePanel


