from setuptools import setup, find_packages

setup(name='z3c.widgets.flashupload',
      version='1.0c1',
      author = "Zope Community",
      author_email = "zope-dev@zope.org",
      description = "Zope Flash Upload Widget",
      long_description=".. contents::\n\n" +
                        open("README.txt").read() + "\n" +
                        open("CHANGES.txt").read(),
      license = "ZPL 2.1",
      keywords = "zope",
      url='http://pypi.python.org/pypi/z3c.widgets.flashupload',
      zip_safe=False,
      packages=find_packages('src'),
      include_package_data=True,
      package_dir = {'':'src'},
      namespace_packages=['z3c', 'z3c.widgets', ],
      extras_require = dict(test=[
          'zope.testing',
          'zope.app.testing',
      ]),
      install_requires = [
          'setuptools',
          'zope.component',
          'zope.event',
          'zope.filerepresentation',
          'zope.i18nmessageid',
          'zope.interface',
          'zope.publisher',
          'zope.security',
          'zope.traversing',
          'zope.app.cache',
          'zope.app.component',
          'zope.app.container',
          'zope.app.pagetemplate',
      ],
      classifiers = ['Environment :: Web Environment',
                     'Framework :: Zope3',
                     'Intended Audience :: Developers',
                     'License :: OSI Approved :: Zope Public License',
                     'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
                     'Programming Language :: Python',
                     ],
      )
