from django.conf.urls.defaults import *

urlpatterns = patterns('',
	(r'^admin/billing/$', 'django.contrib.billing.views.hello'),
	(r'^admin/billing/account/$', 'django.contrib.billing.views.account_list'),
	(r'^admin/billing/account/(\d+)/$', 'django.contrib.billing.views.account_show', { 'template' : "account_receipt.html"}),
	(r'^admin/billing/account/(\d+)/edit/$', 'django.contrib.billing.views.account_edit'),
	(r'^admin/billing/account/(\d+)/payment/$', 'django.contrib.billing.views.payment_add'),
	(r'^admin/billing/account/(\d+)/receipt/$', 'django.contrib.billing.views.account_show', { 'template' : "account_receipt.html"}),
	(r'^admin/billing/account/(\d+)/receipt/current/$', 'django.contrib.billing.views.current_receipt'),
	(r'^admin/billing/account/(\d+)/consumer/$', 'django.contrib.billing.views.account_consumer', { 'template' : "account_consumer.html"}),
	(r'^admin/billing/account/(\d+)/consumer/(\d+)/$', 'django.contrib.billing.views.consumer_charges', { 'template' : "consumer_charges.html"}),
	(r'^admin/billing/account/(\d+)/rateplan/$', 'django.contrib.billing.views.account_rateplan', { 'template' : "account_rateplan.html"}),
#	(r'^admin/billing/account/add/$', 'django.contrib.billing.views.account_add'),
	(r'^admin/billing/account/stats/$', 'django.contrib.billing.views.account_stats'),
	(r'^admin/billing/itemrecord/', handler404),
#	(r'^admin/billing/rateplan/', handler404),
	(r'^admin/billing/rating/', handler404),
	(r'^admin/billing/receipt/$', 'django.contrib.billing.views.receipt_list'),
	(r'^admin/billing/receipt/(\d+)/$', 'django.contrib.billing.views.receipt_view'),
	(r'^admin/billing/receipt/(\d+)/issue/$', 'django.contrib.billing.views.receipt_issue'),
	(r'^admin/billing/receipt/(\d+)/html/$', 'django.contrib.billing.views.receipt_view', { 'template' : "invoice.html" }),
	(r'^admin/billing/receipt/(\d+)/pdf/$', 'django.contrib.billing.views.receipt_pdf', { 'template' : "invoice.html" }),
	(r'^admin/billing/receipt/(\d+)/charge/$', 'django.contrib.billing.views.charge_add', { 'template' : "charge_add.html"}),
	(r'^admin/billing/receipt/(\d+)/charges/$', 'django.contrib.billing.views.receipt_detail', { 'template' : "receipt_detail.html"}),
	(r'^admin/billing/receipt/(\d+)/charges/([^/]+)/$', 'django.contrib.billing.views.charge_show', { 'template' : "charge_show.html"}),
	(r'^admin/billing/receipt/(\d+)/(\d+)/csv/$', 'django.contrib.billing.views.detail_csv'),
#	(r'^admin/billing/traffic/$', 'django.contrib.billing.views.trafficbymonth'),
#	(r'^admin/billing/traffic/(?P<handler>[^/]+)/(?P<date>[^/]+)/$', 'django.contrib.billing.views.trafficformonth'),
)
