# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../gui/plotter.ui'
#
# Created: Tue May 26 00:08:51 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Plotter(object):
    def setupUi(self, Plotter):
        Plotter.setObjectName("Plotter")
        Plotter.resize(800, 510)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Plotter.sizePolicy().hasHeightForWidth())
        Plotter.setSizePolicy(sizePolicy)
        Plotter.setMinimumSize(QtCore.QSize(800, 510))
        Plotter.setMaximumSize(QtCore.QSize(800, 510))
        self.centralwidget = QtGui.QWidget(Plotter)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = QtGui.QWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(10, 10, 491, 431))
        self.graph.setObjectName("graph")
        self.quit = QtGui.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(320, 448, 80, 29))
        self.quit.setObjectName("quit")
        self.plot = QtGui.QPushButton(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(420, 448, 80, 29))
        self.plot.setObjectName("plot")
        self.grid = QtGui.QCheckBox(self.centralwidget)
        self.grid.setGeometry(QtCore.QRect(10, 448, 101, 25))
        self.grid.setObjectName("grid")
        self.PID = QtGui.QGroupBox(self.centralwidget)
        self.PID.setGeometry(QtCore.QRect(510, 220, 281, 251))
        self.PID.setCheckable(True)
        self.PID.setChecked(False)
        self.PID.setObjectName("PID")
        self.gains = QtGui.QGroupBox(self.PID)
        self.gains.setGeometry(QtCore.QRect(10, 30, 261, 111))
        self.gains.setObjectName("gains")
        self.kd = QtGui.QDoubleSpinBox(self.gains)
        self.kd.setGeometry(QtCore.QRect(110, 80, 141, 28))
        self.kd.setDecimals(8)
        self.kd.setMinimum(-999999999.0)
        self.kd.setMaximum(999999999.0)
        self.kd.setSingleStep(0.1)
        self.kd.setObjectName("kd")
        self.ki = QtGui.QDoubleSpinBox(self.gains)
        self.ki.setGeometry(QtCore.QRect(110, 50, 141, 28))
        self.ki.setDecimals(8)
        self.ki.setMinimum(-999999999.0)
        self.ki.setMaximum(999999999.0)
        self.ki.setSingleStep(0.1)
        self.ki.setObjectName("ki")
        self.kp = QtGui.QDoubleSpinBox(self.gains)
        self.kp.setGeometry(QtCore.QRect(110, 20, 141, 28))
        self.kp.setDecimals(8)
        self.kp.setMinimum(-999999999.0)
        self.kp.setMaximum(999999999.0)
        self.kp.setSingleStep(0.1)
        self.kp.setObjectName("kp")
        self.label_8 = QtGui.QLabel(self.gains)
        self.label_8.setGeometry(QtCore.QRect(82, 83, 20, 20))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtGui.QLabel(self.gains)
        self.label_4.setGeometry(QtCore.QRect(82, 25, 20, 18))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.gains)
        self.label_5.setGeometry(QtCore.QRect(82, 53, 20, 20))
        self.label_5.setObjectName("label_5")
        self.groupBox_4 = QtGui.QGroupBox(self.PID)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 148, 261, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.t_method = QtGui.QComboBox(self.groupBox_4)
        self.t_method.setGeometry(QtCore.QRect(47, 20, 211, 27))
        self.t_method.setObjectName("t_method")
        self.t_method.addItem(QtCore.QString())
        self.t_method.addItem(QtCore.QString())
        self.t_method.addItem(QtCore.QString())
        self.t_method.addItem(QtCore.QString())
        self.t_method.addItem(QtCore.QString())
        self.groupBox_6 = QtGui.QGroupBox(self.PID)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 202, 261, 51))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pid_action = QtGui.QComboBox(self.groupBox_6)
        self.pid_action.setGeometry(QtCore.QRect(47, 20, 211, 27))
        self.pid_action.setObjectName("pid_action")
        self.pid_action.addItem(QtCore.QString())
        self.pid_action.addItem(QtCore.QString())
        self.pid_action.addItem(QtCore.QString())
        self.pid_action.addItem(QtCore.QString())
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(510, 10, 281, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 101))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.tf_den = QtGui.QLineEdit(self.groupBox)
        self.tf_den.setGeometry(QtCore.QRect(130, 60, 113, 29))
        self.tf_den.setObjectName("tf_den")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 81, 19))
        self.label_3.setObjectName("label_3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 32, 31, 19))
        self.label.setObjectName("label")
        self.tf_num = QtGui.QLineEdit(self.groupBox)
        self.tf_num.setGeometry(QtCore.QRect(130, 22, 113, 29))
        self.tf_num.setObjectName("tf_num")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 62, 31, 19))
        self.label_2.setObjectName("label_2")
        self.input_box = QtGui.QGroupBox(self.tab)
        self.input_box.setGeometry(QtCore.QRect(10, 107, 251, 51))
        self.input_box.setObjectName("input_box")
        self.parabola = QtGui.QRadioButton(self.input_box)
        self.parabola.setGeometry(QtCore.QRect(170, 20, 81, 25))
        self.parabola.setObjectName("parabola")
        self.step = QtGui.QRadioButton(self.input_box)
        self.step.setGeometry(QtCore.QRect(30, 20, 61, 25))
        self.step.setChecked(True)
        self.step.setObjectName("step")
        self.ramp = QtGui.QRadioButton(self.input_box)
        self.ramp.setGeometry(QtCore.QRect(100, 20, 61, 25))
        self.ramp.setObjectName("ramp")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 261, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.sim_time = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sim_time.setGeometry(QtCore.QRect(170, 60, 91, 29))
        self.sim_time.setDecimals(2)
        self.sim_time.setMinimum(0.01)
        self.sim_time.setMaximum(99.99)
        self.sim_time.setSingleStep(0.5)
        self.sim_time.setProperty("value", QtCore.QVariant(10.0))
        self.sim_time.setObjectName("sim_time")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 25, 121, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 65, 141, 20))
        self.label_7.setObjectName("label_7")
        self.sample_time = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.sample_time.setGeometry(QtCore.QRect(170, 20, 91, 29))
        self.sample_time.setDecimals(4)
        self.sample_time.setMinimum(0.0001)
        self.sample_time.setMaximum(99.9999)
        self.sample_time.setSingleStep(0.01)
        self.sample_time.setProperty("value", QtCore.QVariant(0.01))
        self.sample_time.setObjectName("sample_time")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 110, 261, 51))
        self.groupBox_5.setObjectName("groupBox_5")
        self.n_method = QtGui.QComboBox(self.groupBox_5)
        self.n_method.setGeometry(QtCore.QRect(67, 20, 191, 27))
        self.n_method.setObjectName("n_method")
        self.n_method.addItem(QtCore.QString())
        self.n_method.addItem(QtCore.QString())
        self.n_method.addItem(QtCore.QString())
        self.n_method.addItem(QtCore.QString())
        self.tabWidget.addTab(self.tab_2, "")
        Plotter.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Plotter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        Plotter.setMenuBar(self.menubar)
        self.actionSave = QtGui.QAction(Plotter)
        self.actionSave.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(Plotter)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_TFP = QtGui.QAction(Plotter)
        self.actionAbout_TFP.setObjectName("actionAbout_TFP")
        self.actionAboutQT = QtGui.QAction(Plotter)
        self.actionAboutQT.setObjectName("actionAboutQT")
        self.action_State_Space_Model = QtGui.QAction(Plotter)
        self.action_State_Space_Model.setObjectName("action_State_Space_Model")
        self.actionWeb_Page = QtGui.QAction(Plotter)
        self.actionWeb_Page.setObjectName("actionWeb_Page")
        self.actionAbout_Qt = QtGui.QAction(Plotter)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_PythonControl_Systems = QtGui.QAction(Plotter)
        self.actionAbout_PythonControl_Systems.setObjectName("actionAbout_PythonControl_Systems")
        self.actionAbout_PCS = QtGui.QAction(Plotter)
        self.actionAbout_PCS.setObjectName("actionAbout_PCS")
        self.actionAbout_QT = QtGui.QAction(Plotter)
        self.actionAbout_QT.setObjectName("actionAbout_QT")
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout_TFP)
        self.menuAbout.addAction(self.actionAbout_PCS)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout_QT)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Plotter)
        self.tabWidget.setCurrentIndex(0)
        self.n_method.setCurrentIndex(0)
        QtCore.QObject.connect(self.quit, QtCore.SIGNAL("clicked()"), Plotter.close)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), Plotter.close)
        QtCore.QMetaObject.connectSlotsByName(Plotter)
        Plotter.setTabOrder(self.tabWidget, self.tf_num)
        Plotter.setTabOrder(self.tf_num, self.tf_den)
        Plotter.setTabOrder(self.tf_den, self.step)
        Plotter.setTabOrder(self.step, self.ramp)
        Plotter.setTabOrder(self.ramp, self.parabola)
        Plotter.setTabOrder(self.parabola, self.sample_time)
        Plotter.setTabOrder(self.sample_time, self.sim_time)
        Plotter.setTabOrder(self.sim_time, self.n_method)
        Plotter.setTabOrder(self.n_method, self.PID)
        Plotter.setTabOrder(self.PID, self.kp)
        Plotter.setTabOrder(self.kp, self.ki)
        Plotter.setTabOrder(self.ki, self.kd)
        Plotter.setTabOrder(self.kd, self.t_method)
        Plotter.setTabOrder(self.t_method, self.pid_action)
        Plotter.setTabOrder(self.pid_action, self.grid)
        Plotter.setTabOrder(self.grid, self.quit)
        Plotter.setTabOrder(self.quit, self.plot)

    def retranslateUi(self, Plotter):
        Plotter.setWindowTitle(QtGui.QApplication.translate("Plotter", "Transfer Functions Plotter", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setText(QtGui.QApplication.translate("Plotter", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.plot.setText(QtGui.QApplication.translate("Plotter", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.grid.setText(QtGui.QApplication.translate("Plotter", "Display Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.PID.setTitle(QtGui.QApplication.translate("Plotter", "PID Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.gains.setTitle(QtGui.QApplication.translate("Plotter", "Gains", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Plotter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Kd</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Plotter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Kp</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Plotter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Ki</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Plotter", "Tuning Method", None, QtGui.QApplication.UnicodeUTF8))
        self.t_method.setItemText(0, QtGui.QApplication.translate("Plotter", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.t_method.setItemText(1, QtGui.QApplication.translate("Plotter", "Ziegler-Nichols", None, QtGui.QApplication.UnicodeUTF8))
        self.t_method.setItemText(2, QtGui.QApplication.translate("Plotter", "Cohen-Coon", None, QtGui.QApplication.UnicodeUTF8))
        self.t_method.setItemText(3, QtGui.QApplication.translate("Plotter", "Chien-Hrones-Reswick (0%)", None, QtGui.QApplication.UnicodeUTF8))
        self.t_method.setItemText(4, QtGui.QApplication.translate("Plotter", "Chien-Hrones-Reswick (20%)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Plotter", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.pid_action.setItemText(0, QtGui.QApplication.translate("Plotter", "PID", None, QtGui.QApplication.UnicodeUTF8))
        self.pid_action.setItemText(1, QtGui.QApplication.translate("Plotter", "Proportional", None, QtGui.QApplication.UnicodeUTF8))
        self.pid_action.setItemText(2, QtGui.QApplication.translate("Plotter", "Integral", None, QtGui.QApplication.UnicodeUTF8))
        self.pid_action.setItemText(3, QtGui.QApplication.translate("Plotter", "Derivative", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Plotter", "Transfer Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Plotter", "_________ =", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Plotter", "N(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Plotter", "D(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.input_box.setTitle(QtGui.QApplication.translate("Plotter", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.parabola.setText(QtGui.QApplication.translate("Plotter", "Parabola", None, QtGui.QApplication.UnicodeUTF8))
        self.step.setText(QtGui.QApplication.translate("Plotter", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.ramp.setText(QtGui.QApplication.translate("Plotter", "Ramp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Plotter", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Plotter", "Simulation Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Plotter", "Sample Time (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Plotter", "Simulation Time (sec)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Plotter", "Numerical Method", None, QtGui.QApplication.UnicodeUTF8))
        self.n_method.setItemText(0, QtGui.QApplication.translate("Plotter", "Euler", None, QtGui.QApplication.UnicodeUTF8))
        self.n_method.setItemText(1, QtGui.QApplication.translate("Plotter", "Runge-Kutta (Order 2)", None, QtGui.QApplication.UnicodeUTF8))
        self.n_method.setItemText(2, QtGui.QApplication.translate("Plotter", "Runge-Kutta (Order 3)", None, QtGui.QApplication.UnicodeUTF8))
        self.n_method.setItemText(3, QtGui.QApplication.translate("Plotter", "Runge-Kutta (Order 4)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Plotter", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("Plotter", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("Plotter", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Plotter", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Plotter", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_TFP.setText(QtGui.QApplication.translate("Plotter", "About Transfer Functions &Plotter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQT.setText(QtGui.QApplication.translate("Plotter", "About &QT", None, QtGui.QApplication.UnicodeUTF8))
        self.action_State_Space_Model.setText(QtGui.QApplication.translate("Plotter", "&State-Space Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWeb_Page.setText(QtGui.QApplication.translate("Plotter", "&Web Page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("Plotter", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_PythonControl_Systems.setText(QtGui.QApplication.translate("Plotter", "About PythonControl Systems", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_PCS.setText(QtGui.QApplication.translate("Plotter", "About &Python Control Systems", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_QT.setText(QtGui.QApplication.translate("Plotter", "About &QT", None, QtGui.QApplication.UnicodeUTF8))

