# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'improviser/qtGUI/improviser.ui'
#
# Created: Wed Jan 14 20:08:28 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 510)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtGui.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 10, 801, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.Tabs.setElideMode(QtCore.Qt.ElideLeft)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.label_4.setObjectName("label_4")
        self.projectname = QtGui.QLineEdit(self.tab)
        self.projectname.setGeometry(QtCore.QRect(120, 20, 391, 23))
        self.projectname.setObjectName("projectname")
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 100, 91, 17))
        self.label_11.setObjectName("label_11")
        self.visualization = QtGui.QComboBox(self.tab)
        self.visualization.setGeometry(QtCore.QRect(120, 100, 171, 22))
        self.visualization.setObjectName("visualization")
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 56, 17))
        self.label_12.setObjectName("label_12")
        self.author = QtGui.QLineEdit(self.tab)
        self.author.setGeometry(QtCore.QRect(120, 60, 391, 23))
        self.author.setObjectName("author")
        self.Tabs.addTab(self.tab, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.movement = QtGui.QComboBox(self.tab_5)
        self.movement.setGeometry(QtCore.QRect(150, 20, 141, 22))
        self.movement.setObjectName("movement")
        self.label_8 = QtGui.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 81, 17))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 56, 17))
        self.label_5.setObjectName("label_5")
        self.loop = QtGui.QSpinBox(self.tab_5)
        self.loop.setGeometry(QtCore.QRect(150, 60, 81, 23))
        self.loop.setMaximum(10000)
        self.loop.setProperty("value", QtCore.QVariant(1))
        self.loop.setObjectName("loop")
        self.label = QtGui.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(20, 100, 111, 17))
        self.label.setObjectName("label")
        self.resolution = QtGui.QComboBox(self.tab_5)
        self.resolution.setGeometry(QtCore.QRect(150, 220, 141, 22))
        self.resolution.setObjectName("resolution")
        self.duration = QtGui.QSpinBox(self.tab_5)
        self.duration.setGeometry(QtCore.QRect(150, 300, 141, 23))
        self.duration.setMinimum(1)
        self.duration.setMaximum(1000)
        self.duration.setProperty("value", QtCore.QVariant(1))
        self.duration.setObjectName("duration")
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 101, 17))
        self.label_7.setObjectName("label_7")
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_2.setObjectName("label_2")
        self.swing = QtGui.QCheckBox(self.tab_5)
        self.swing.setGeometry(QtCore.QRect(700, 340, 83, 22))
        self.swing.setObjectName("swing")
        self.bpm = QtGui.QSpinBox(self.tab_5)
        self.bpm.setGeometry(QtCore.QRect(150, 100, 81, 23))
        self.bpm.setMinimum(1)
        self.bpm.setMaximum(1000)
        self.bpm.setProperty("value", QtCore.QVariant(120))
        self.bpm.setObjectName("bpm")
        self.wildness = QtGui.QDoubleSpinBox(self.tab_5)
        self.wildness.setGeometry(QtCore.QRect(150, 140, 81, 23))
        self.wildness.setDecimals(5)
        self.wildness.setMaximum(100.0)
        self.wildness.setSingleStep(0.025)
        self.wildness.setProperty("value", QtCore.QVariant(0.5))
        self.wildness.setObjectName("wildness")
        self.key = QtGui.QComboBox(self.tab_5)
        self.key.setGeometry(QtCore.QRect(150, 260, 141, 22))
        self.key.setObjectName("key")
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 101, 17))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 111, 17))
        self.label_3.setObjectName("label_3")
        self.bpmslide = QtGui.QSlider(self.tab_5)
        self.bpmslide.setGeometry(QtCore.QRect(250, 100, 160, 16))
        self.bpmslide.setPageStep(10)
        self.bpmslide.setProperty("value", QtCore.QVariant(50))
        self.bpmslide.setOrientation(QtCore.Qt.Horizontal)
        self.bpmslide.setObjectName("bpmslide")
        self.wildslide = QtGui.QSlider(self.tab_5)
        self.wildslide.setGeometry(QtCore.QRect(250, 140, 160, 16))
        self.wildslide.setProperty("value", QtCore.QVariant(1))
        self.wildslide.setOrientation(QtCore.Qt.Horizontal)
        self.wildslide.setObjectName("wildslide")
        self.loopslide = QtGui.QSlider(self.tab_5)
        self.loopslide.setGeometry(QtCore.QRect(250, 60, 160, 16))
        self.loopslide.setPageStep(10)
        self.loopslide.setProperty("value", QtCore.QVariant(1))
        self.loopslide.setOrientation(QtCore.Qt.Horizontal)
        self.loopslide.setObjectName("loopslide")
        self.Tabs.addTab(self.tab_5, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.addblockbutton = QtGui.QPushButton(self.tab_3)
        self.addblockbutton.setGeometry(QtCore.QRect(700, 10, 80, 27))
        self.addblockbutton.setObjectName("addblockbutton")
        self.removeblock = QtGui.QPushButton(self.tab_3)
        self.removeblock.setEnabled(True)
        self.removeblock.setGeometry(QtCore.QRect(700, 300, 80, 27))
        self.removeblock.setObjectName("removeblock")
        self.editblock = QtGui.QPushButton(self.tab_3)
        self.editblock.setEnabled(True)
        self.editblock.setGeometry(QtCore.QRect(700, 50, 80, 27))
        self.editblock.setObjectName("editblock")
        self.blocks = QtGui.QListWidget(self.tab_3)
        self.blocks.setGeometry(QtCore.QRect(10, 10, 671, 361))
        self.blocks.setObjectName("blocks")
        self.upblock = QtGui.QPushButton(self.tab_3)
        self.upblock.setGeometry(QtCore.QRect(700, 220, 80, 27))
        self.upblock.setObjectName("upblock")
        self.downblock = QtGui.QPushButton(self.tab_3)
        self.downblock.setGeometry(QtCore.QRect(700, 260, 80, 27))
        self.downblock.setObjectName("downblock")
        self.clearblocks = QtGui.QPushButton(self.tab_3)
        self.clearblocks.setGeometry(QtCore.QRect(700, 340, 80, 27))
        self.clearblocks.setObjectName("clearblocks")
        self.Tabs.addTab(self.tab_3, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.addinstrumentbutton = QtGui.QPushButton(self.tab_2)
        self.addinstrumentbutton.setGeometry(QtCore.QRect(700, 10, 80, 27))
        self.addinstrumentbutton.setObjectName("addinstrumentbutton")
        self.editinstrument = QtGui.QPushButton(self.tab_2)
        self.editinstrument.setEnabled(True)
        self.editinstrument.setGeometry(QtCore.QRect(700, 50, 80, 27))
        self.editinstrument.setObjectName("editinstrument")
        self.removeinstrument = QtGui.QPushButton(self.tab_2)
        self.removeinstrument.setEnabled(True)
        self.removeinstrument.setGeometry(QtCore.QRect(700, 300, 80, 27))
        self.removeinstrument.setObjectName("removeinstrument")
        self.instrumentcombo = QtGui.QComboBox(self.tab_2)
        self.instrumentcombo.setGeometry(QtCore.QRect(10, 10, 671, 22))
        self.instrumentcombo.setObjectName("instrumentcombo")
        self.instruments = QtGui.QListWidget(self.tab_2)
        self.instruments.setGeometry(QtCore.QRect(10, 40, 671, 331))
        self.instruments.setObjectName("instruments")
        self.clearinstruments = QtGui.QPushButton(self.tab_2)
        self.clearinstruments.setGeometry(QtCore.QRect(700, 340, 80, 27))
        self.clearinstruments.setObjectName("clearinstruments")
        self.upinstrument = QtGui.QPushButton(self.tab_2)
        self.upinstrument.setGeometry(QtCore.QRect(700, 220, 80, 27))
        self.upinstrument.setObjectName("upinstrument")
        self.downinstrument = QtGui.QPushButton(self.tab_2)
        self.downinstrument.setGeometry(QtCore.QRect(700, 260, 80, 27))
        self.downinstrument.setObjectName("downinstrument")
        self.Tabs.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.addprogressionbutton = QtGui.QPushButton(self.tab_4)
        self.addprogressionbutton.setGeometry(QtCore.QRect(700, 10, 80, 27))
        self.addprogressionbutton.setObjectName("addprogressionbutton")
        self.editprogression = QtGui.QPushButton(self.tab_4)
        self.editprogression.setEnabled(True)
        self.editprogression.setGeometry(QtCore.QRect(700, 50, 80, 27))
        self.editprogression.setObjectName("editprogression")
        self.removeprogression = QtGui.QPushButton(self.tab_4)
        self.removeprogression.setEnabled(True)
        self.removeprogression.setGeometry(QtCore.QRect(700, 300, 80, 27))
        self.removeprogression.setObjectName("removeprogression")
        self.progressioncombo = QtGui.QComboBox(self.tab_4)
        self.progressioncombo.setGeometry(QtCore.QRect(10, 10, 671, 22))
        self.progressioncombo.setObjectName("progressioncombo")
        self.progressions = QtGui.QListWidget(self.tab_4)
        self.progressions.setGeometry(QtCore.QRect(10, 40, 671, 331))
        self.progressions.setObjectName("progressions")
        self.upprogression = QtGui.QPushButton(self.tab_4)
        self.upprogression.setGeometry(QtCore.QRect(700, 220, 80, 27))
        self.upprogression.setObjectName("upprogression")
        self.downprogression = QtGui.QPushButton(self.tab_4)
        self.downprogression.setGeometry(QtCore.QRect(700, 260, 80, 27))
        self.downprogression.setObjectName("downprogression")
        self.clearprogressions = QtGui.QPushButton(self.tab_4)
        self.clearprogressions.setGeometry(QtCore.QRect(700, 340, 80, 27))
        self.clearprogressions.setObjectName("clearprogressions")
        self.Tabs.addTab(self.tab_4, "")
        self.startbutton = QtGui.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(550, 430, 80, 27))
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtGui.QPushButton(self.centralwidget)
        self.stopbutton.setEnabled(False)
        self.stopbutton.setGeometry(QtCore.QRect(640, 430, 80, 27))
        self.stopbutton.setObjectName("stopbutton")
        self.uploadbutton = QtGui.QPushButton(self.centralwidget)
        self.uploadbutton.setEnabled(False)
        self.uploadbutton.setGeometry(QtCore.QRect(730, 430, 80, 27))
        self.uploadbutton.setObjectName("uploadbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setMenuRole(QtGui.QAction.ApplicationSpecificRole)
        self.action_Load.setObjectName("action_Load")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.actionS_ave_as = QtGui.QAction(MainWindow)
        self.actionS_ave_as.setObjectName("actionS_ave_as")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.action_Load)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionS_ave_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionE_xit)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionE_xit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.blocks, QtCore.SIGNAL("doubleClicked(QModelIndex)"), self.editblock.click)
        QtCore.QObject.connect(self.instruments, QtCore.SIGNAL("doubleClicked(QModelIndex)"), self.editinstrument.click)
        QtCore.QObject.connect(self.progressions, QtCore.SIGNAL("doubleClicked(QModelIndex)"), self.editprogression.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "qtImproviser - Untitled.imp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Project name", None, QtGui.QApplication.UnicodeUTF8))
        self.projectname.setText(QtGui.QApplication.translate("MainWindow", "Untitled", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Visualization", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.movement.setStatusTip(QtGui.QApplication.translate("MainWindow", "The movement dictates the order of the blocks, progressions and instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setStatusTip(QtGui.QApplication.translate("MainWindow", "The movement dictates the order of the blocks, progressions and instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Movement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many times the movement should be looped", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.loop.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many times the movement should be looped", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Default BPM", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many times a block should be played", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Block duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Default wildness", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setStatusTip(QtGui.QApplication.translate("MainWindow", "Swing the notes", None, QtGui.QApplication.UnicodeUTF8))
        self.swing.setText(QtGui.QApplication.translate("MainWindow", "Swing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Default key", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Default resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Movement", None, QtGui.QApplication.UnicodeUTF8))
        self.addblockbutton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.removeblock.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.editblock.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.upblock.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.downblock.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.clearblocks.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.addinstrumentbutton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.editinstrument.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.removeinstrument.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.clearinstruments.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.upinstrument.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.downinstrument.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Instruments", None, QtGui.QApplication.UnicodeUTF8))
        self.addprogressionbutton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.editprogression.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.removeprogression.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.upprogression.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.downprogression.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.clearprogressions.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Progressions", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Start generating music", None, QtGui.QApplication.UnicodeUTF8))
        self.startbutton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Stop generating music", None, QtGui.QApplication.UnicodeUTF8))
        self.stopbutton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadbutton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Upload midi to the Improviser homepage", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadbutton.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setToolTip(QtGui.QApplication.translate("MainWindow", "Load a previously saved project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setStatusTip(QtGui.QApplication.translate("MainWindow", "Load a previously saved project", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionS_ave_as.setText(QtGui.QApplication.translate("MainWindow", "S&ave as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))

