
#!/usr/bin/env python
# Generated by pykdeuic4 from ID3EncodingConverter.ui on Sun Apr 20 19:22:50 2008
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui
from PyKDE4.kdeui import KComboBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(QtCore.QSize(QtCore.QRect(0,0,573,498).size()).expandedTo(MainWindow.minimumSizeHint()))

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)

        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")

        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setObjectName("treeView")
        self.vboxlayout.addWidget(self.treeView)

        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")

        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")

        self.titlelabel = QtGui.QLabel(self.centralwidget)
        self.titlelabel.setObjectName("titlelabel")
        self.gridlayout.addWidget(self.titlelabel,1,0,1,1)

        self.v1title = KComboBox(self.centralwidget)
        self.v1title.setModelColumn(0)
        self.v1title.setObjectName("v1title")
        self.gridlayout.addWidget(self.v1title,1,1,1,1)

        self.v2title = QtGui.QLineEdit(self.centralwidget)
        self.v2title.setAutoFillBackground(False)
        self.v2title.setObjectName("v2title")
        self.gridlayout.addWidget(self.v2title,1,3,1,1)

        self.artistlabel = QtGui.QLabel(self.centralwidget)
        self.artistlabel.setObjectName("artistlabel")
        self.gridlayout.addWidget(self.artistlabel,2,0,1,1)

        self.v1artist = QtGui.QLineEdit(self.centralwidget)
        self.v1artist.setReadOnly(True)
        self.v1artist.setObjectName("v1artist")
        self.gridlayout.addWidget(self.v1artist,2,1,1,1)

        self.v2artist = QtGui.QLineEdit(self.centralwidget)
        self.v2artist.setObjectName("v2artist")
        self.gridlayout.addWidget(self.v2artist,2,3,1,1)

        self.albumlabel = QtGui.QLabel(self.centralwidget)
        self.albumlabel.setObjectName("albumlabel")
        self.gridlayout.addWidget(self.albumlabel,3,0,1,1)

        self.v1album = QtGui.QLineEdit(self.centralwidget)
        self.v1album.setReadOnly(True)
        self.v1album.setObjectName("v1album")
        self.gridlayout.addWidget(self.v1album,3,1,1,1)

        self.v2album = QtGui.QLineEdit(self.centralwidget)
        self.v2album.setObjectName("v2album")
        self.gridlayout.addWidget(self.v2album,3,3,1,1)

        self.genrelabel = QtGui.QLabel(self.centralwidget)
        self.genrelabel.setObjectName("genrelabel")
        self.gridlayout.addWidget(self.genrelabel,4,0,1,1)

        self.v1genre = QtGui.QLineEdit(self.centralwidget)
        self.v1genre.setReadOnly(True)
        self.v1genre.setObjectName("v1genre")
        self.gridlayout.addWidget(self.v1genre,4,1,1,1)

        self.v2genre = QtGui.QLineEdit(self.centralwidget)
        self.v2genre.setObjectName("v2genre")
        self.gridlayout.addWidget(self.v2genre,4,3,1,1)

        self.commentlabel = QtGui.QLabel(self.centralwidget)
        self.commentlabel.setObjectName("commentlabel")
        self.gridlayout.addWidget(self.commentlabel,5,0,1,1)

        self.v1comment = QtGui.QLineEdit(self.centralwidget)
        self.v1comment.setReadOnly(True)
        self.v1comment.setObjectName("v1comment")
        self.gridlayout.addWidget(self.v1comment,5,1,1,1)

        self.v2comment = QtGui.QLineEdit(self.centralwidget)
        self.v2comment.setObjectName("v2comment")
        self.gridlayout.addWidget(self.v2comment,5,3,1,1)

        self.convertTitleButton = QtGui.QPushButton(self.centralwidget)
        self.convertTitleButton.setObjectName("convertTitleButton")
        self.gridlayout.addWidget(self.convertTitleButton,1,2,1,1)

        self.convertArtistButton = QtGui.QPushButton(self.centralwidget)
        self.convertArtistButton.setObjectName("convertArtistButton")
        self.gridlayout.addWidget(self.convertArtistButton,2,2,1,1)

        self.convertAlbumButton = QtGui.QPushButton(self.centralwidget)
        self.convertAlbumButton.setObjectName("convertAlbumButton")
        self.gridlayout.addWidget(self.convertAlbumButton,3,2,1,1)

        self.convertGenreButton = QtGui.QPushButton(self.centralwidget)
        self.convertGenreButton.setObjectName("convertGenreButton")
        self.gridlayout.addWidget(self.convertGenreButton,4,2,1,1)

        self.convertCommentButton = QtGui.QPushButton(self.centralwidget)
        self.convertCommentButton.setObjectName("convertCommentButton")
        self.gridlayout.addWidget(self.convertCommentButton,5,2,1,1)

        self.convertAllButton = QtGui.QPushButton(self.centralwidget)
        self.convertAllButton.setIconSize(QtCore.QSize(20,20))
        self.convertAllButton.setObjectName("convertAllButton")
        self.gridlayout.addWidget(self.convertAllButton,0,2,1,1)

        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")

        self.v1label = QtGui.QLabel(self.centralwidget)
        self.v1label.setTextFormat(QtCore.Qt.PlainText)
        self.v1label.setObjectName("v1label")
        self.hboxlayout.addWidget(self.v1label)

        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)

        self.v1removeButton = QtGui.QPushButton(self.centralwidget)
        self.v1removeButton.setIconSize(QtCore.QSize(20,20))
        self.v1removeButton.setObjectName("v1removeButton")
        self.hboxlayout.addWidget(self.v1removeButton)
        self.gridlayout.addLayout(self.hboxlayout,0,1,1,1)

        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")

        self.v2label = QtGui.QLabel(self.centralwidget)
        self.v2label.setObjectName("v2label")
        self.hboxlayout1.addWidget(self.v2label)

        spacerItem1 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)

        self.v2recode = QtGui.QPushButton(self.centralwidget)
        self.v2recode.setIconSize(QtCore.QSize(20,20))
        self.v2recode.setObjectName("v2recode")
        self.hboxlayout1.addWidget(self.v2recode)
        self.gridlayout.addLayout(self.hboxlayout1,0,3,1,1)
        self.vboxlayout1.addLayout(self.gridlayout)
        self.vboxlayout.addLayout(self.vboxlayout1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.titlelabel.setBuddy(self.v2title)
        self.artistlabel.setBuddy(self.v2artist)
        self.albumlabel.setBuddy(self.v2album)
        self.genrelabel.setBuddy(self.v2genre)
        self.commentlabel.setBuddy(self.v2comment)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.v2title,self.v1artist)
        MainWindow.setTabOrder(self.v1artist,self.v2artist)
        MainWindow.setTabOrder(self.v2artist,self.v1album)
        MainWindow.setTabOrder(self.v1album,self.v2album)
        MainWindow.setTabOrder(self.v2album,self.v1genre)
        MainWindow.setTabOrder(self.v1genre,self.v2genre)
        MainWindow.setTabOrder(self.v2genre,self.v1comment)
        MainWindow.setTabOrder(self.v1comment,self.v2comment)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(kdecore.i18n("ID3EncodingConverter"))
        self.titlelabel.setText(kdecore.i18n("&Title"))
        self.v1title.setToolTip(kdecore.i18n("Choose correct representation of song title"))
        self.v1title.setWhatsThis(kdecore.i18n("Choose the correct encoding of the ID3v1 tag. All tags beneath will be updated according to the selection. If the actual encoding is unknown, choose the string that makes sense."))
        self.artistlabel.setText(kdecore.i18n("A&rtist"))
        self.albumlabel.setText(kdecore.i18n("A&lbum"))
        self.genrelabel.setText(kdecore.i18n("&Genre"))
        self.commentlabel.setText(kdecore.i18n("&Comment"))
        self.convertTitleButton.setToolTip(kdecore.i18n("Copy song title"))
        self.convertTitleButton.setWhatsThis(kdecore.i18n("Copy the title tag from ID3v1 to ID3v2."))
        self.convertArtistButton.setToolTip(kdecore.i18n("Copy artist"))
        self.convertArtistButton.setWhatsThis(kdecore.i18n("Copy the artist tag from ID3v1 to ID3v2."))
        self.convertAlbumButton.setToolTip(kdecore.i18n("Copy album"))
        self.convertAlbumButton.setWhatsThis(kdecore.i18n("Copy the album tag from ID3v1 to ID3v2."))
        self.convertGenreButton.setToolTip(kdecore.i18n("Copy genre"))
        self.convertGenreButton.setWhatsThis(kdecore.i18n("Copy the genre tag from ID3v1 to ID3v2."))
        self.convertCommentButton.setToolTip(kdecore.i18n("Copy comment"))
        self.convertCommentButton.setWhatsThis(kdecore.i18n("Copy the comment tag from ID3v1 to ID3v2."))
        self.convertAllButton.setToolTip(kdecore.i18n("Convert all tags to ID3v2"))
        self.convertAllButton.setWhatsThis(kdecore.i18n("Copy all tags from ID3v1 to ID3v2."))
        self.v1label.setText(kdecore.i18n("ID3v1"))
        self.v1removeButton.setToolTip(kdecore.i18n("Delete ID3v1 tag"))
        self.v1removeButton.setWhatsThis(kdecore.i18n("This deletes the ID3v1 tag and can be used once it was converted to ID3v2."))
        self.v2label.setText(kdecore.i18n("ID3v2"))
        self.v2recode.setToolTip(kdecore.i18n("Repair encoding of ID3v2 tag"))
        self.v2recode.setWhatsThis(kdecore.i18n("This repairs the encoding of the ID3v2 tag when the tag was encoded in something different then the standard Unicode."))
