#  This file is automatically generated; please don't muck it up!

#--begin constants--

ENDMARKER = 512
NAME = 513
NUMBER = 514
STRING = 515
NEWLINE = 516
INDENT = 517
DEDENT = 518
LPAR = 519
RPAR = 520
LSQB = 521
RSQB = 522
COLON = 523
COMMA = 524
SEMI = 525
PLUS = 526
MINUS = 527
STAR = 528
SLASH = 529
VBAR = 530
AMPER = 531
LESS = 532
GREATER = 533
EQUAL = 534
DOT = 535
PERCENT = 536
BACKQUOTE = 537
LBRACE = 538
RBRACE = 539
EQEQUAL = 540
NOTEQUAL = 541
LESSEQUAL = 542
GREATEREQUAL = 543
TILDE = 544
CIRCUMFLEX = 545
LEFTSHIFT = 546
RIGHTSHIFT = 547
DOUBLESTAR = 548
PLUSEQUAL = 549
MINEQUAL = 550
STAREQUAL = 551
SLASHEQUAL = 552
PERCENTEQUAL = 553
AMPEREQUAL = 554
VBAREQUAL = 555
CIRCUMFLEXEQUAL = 556
LEFTSHIFTEQUAL = 557
RIGHTSHIFTEQUAL = 558
DOUBLESTAREQUAL = 559
DOUBLESLASH = 560
DOUBLESLASHEQUAL = 561
AT = 562
OP = 563
ERRORTOKEN = 564
COMMENT = 565
NL = 566
N_TOKENS = 567
token_input = 568
unit = 569
char_start = 570
dot_start = 571
LINECONT = 572
LINE_COMMENT = 573
WHITE = 574
INTRON = 575
Longnumber = 576
Intnumber = 577
Hexnumber = 578
Octnumber = 579
Decnumber = 580
Imagnumber = 581
Floatnumber = 582
Pointfloat = 583
Expfloat = 584
Exponent = 585
STR_PREFIX = 586
Single = 587
_value = 587
Double = 588
Single3 = 589
Double3 = 590
Number = 591
OPERATOR = 592
RIGHT = 593
LEFT = 594
SPECIAL = 595
LEFT_DEF = 596
RIGHT_DEF = 597
SPECIAL_DEF = 598
OPERATOR_DEF = 599
IPv4Address = 600
Triple = 601

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name


token_map = {'!=': 541,
 '""""""(ANY|""|""ANY*"")*""""""': 589,
 '"""(ANY|"|"ANY*")*"""': 590,
 '""(A_BACKSLASHANY|ANY)*""': 587,
 '"(A_BACKSLASHANY|ANY)*"': 588,
 '#': 573,
 '%': 536,
 '%=': 553,
 '&': 531,
 '&=': 554,
 '(': 519,
 '(0(x|X)A_HEX_DIGIT+|0A_OCT_DIGIT*|A_NON_NULL_DIGITA_DIGIT*)[l|L|Exponent[j|J]|j|J]|(A_DIGIT+.A_DIGIT*[Exponent])[j|J]': 591,
 '(Intnumber|Floatnumber)(j|J)': 581,
 '(PLUS|MINUS|STAR|SLASH|VBAR|AMPER|LESS|GREATER|EQUAL|PERCENT|EQEQUAL|NOTEQUAL|LESSEQUAL|GREATEREQUAL|TILDE|CIRCUMFLEX|LEFTSHIFT|RIGHTSHIFT|DOUBLESTAR|PLUSEQUAL|MINEQUAL|STAREQUAL|SLASHEQUAL|PERCENTEQUAL|AMPEREQUAL|VBAREQUAL|CIRCUMFLEXEQUAL|LEFTSHIFTEQUAL|RIGHTSHIFTEQUAL|DOUBLESTAREQUAL|DOUBLESLASH|DOUBLESLASHEQUAL)': 599,
 '(e|E)[-|+]A_DIGIT+': 585,
 ')': 520,
 '*': 528,
 '**': 548,
 '**=': 559,
 '*=': 551,
 '+': 526,
 '+=': 549,
 ',': 524,
 '-': 527,
 '-=': 550,
 '.': 535,
 '.|.A_DIGIT+[Exponent][j|J]': 571,
 '/': 529,
 '//': 560,
 '//=': 561,
 '/=': 552,
 '0(x|X)A_HEX_DIGIT+': 578,
 '0A_OCT_DIGIT+': 579,
 '0|(A_NON_NULL_DIGITA_DIGIT*)': 580,
 ':': 523,
 ';': 525,
 '<': 532,
 '<<': 546,
 '<<=': 557,
 '<=': 542,
 '=': 534,
 '==': 540,
 '>': 533,
 '>=': 543,
 '>>': 547,
 '>>=': 558,
 '@': 562,
 'A_BACKSLASHA_WHITE*[A_LINE_END|COMMENT]': 572,
 'A_CHAR(A_CHAR|A_DIGIT)*': 513,
 'A_DIGIT+.A_DIGIT*[Exponent]|.A_DIGIT+[Exponent]': 583,
 'A_DIGIT[A_DIGIT][A_DIGIT]': 601,
 'A_WHITE+': 574,
 'COMMA|SEMI|BACKQUOTE|AT': 598,
 'COMMENT|(WHITE[COMMENT])+|LINECONT': 575,
 'Hexnumber|Octnumber|Decnumber': 577,
 'Intnumber(l|L)': 576,
 'IntnumberExponent': 584,
 'LEFT_DEF': 594,
 'LINE_COMMENTANY*A_LINE_END+': 565,
 'LPAR|LSQB|LBRACE': 596,
 'Number': 514,
 'OPERATOR_DEF': 592,
 'Pointfloat|Expfloat': 582,
 'RIGHT_DEF': 593,
 'RPAR|RSQB|RBRACE': 597,
 'SPECIAL_DEF': 595,
 'STRING|NAME': 570,
 'T_DEDENT': 518,
 'T_ENDMARKER': 512,
 'T_ERRORTOKEN': 564,
 'T_INDENT': 517,
 'T_NEWLINE': 516,
 'T_NT': 566,
 'T_N_TOKENS': 567,
 'T_OP': 563,
 'Triple.Triple.Triple.Triple': 600,
 '[': 521,
 '[STR_PREFIX](Single|Double|Single3|Double3)': 515,
 ']': 522,
 '^': 545,
 '^=': 556,
 '`': 537,
 'char_start|dot_start|NEWLINE|NUMBER|LEFT|RIGHT|SPECIAL|OPERATOR|COLON|INTRON|IPv4Address': 569,
 'u[r|R]|U[r|R]|r|R': 586,
 'unit*ENDMARKER': 568,
 '{': 538,
 '|': 530,
 '|=': 555,
 '}': 539,
 '~': 544}

