#!python
from setuptools import setup, find_packages

setup(name='collective.formwidget.uberselect',
      version='0.1',
      author = "Malthe Borch",
      author_email = "mborch@gmail.com",
      description = "An uberselection widget for z3c.form.",
      long_description=open('README.txt').read(),
      license = "GPL",
      keywords = "zope zope2 z3c.form",
      zip_safe=False,
      packages=find_packages('src'),
      include_package_data=True,
      package_dir = {'':'src'},
      namespace_packages=['collective', 'collective.formwidget'],
      install_requires = ['setuptools',
                          'z3c.form',
                          'zope.interface',
                          'zope.schema',
                          'zope.i18nmessageid',
                          'z3c.formwidget.query',
                          ],
      classifiers = ['Development Status :: 4 - Beta',
                     'Environment :: Web Environment',
                     'Framework :: Zope3',
                     'Intended Audience :: Developers',
                     'License :: OSI Approved :: Zope Public License',
                     'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
                     'Programming Language :: Python',
                     'Topic :: Software Development :: Libraries :: Python Modules',
                     ],
      )
