#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'1.00',
 'build_date': '2010-03-03 12:34:03 -0800',
 'clean': None,
 'date': '2010-03-02 17:12:18 -0800',
 'revision_id': 'root@peacemaker-20100303011218-e6hamammw0q8cyb6',
 'revno': 730}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
