from devshell.modules.audit import *
from devshell.modules.autotools import *
from devshell.modules.bugs import *
from devshell.modules.build import *
from devshell.modules.buildsystem import *
from devshell.modules.cabal import *
from devshell.modules.darcs import *
from devshell.modules.directory import *
from devshell.modules.fedorahostedgitfetcher import *
from devshell.modules.fedorahostedgitport import *
from devshell.modules.fetcher import *
from devshell.modules.freejport import *
from devshell.modules.git import *
from devshell.modules.hackage import *
from devshell.modules.haskellport import *
from devshell.modules.mail import *
from devshell.modules.mock import *
from devshell.modules.package import *
from devshell.modules.packagesource import *
from devshell.modules.port import *
from devshell.modules.profile import *
from devshell.modules.revisioncontrol import *
from devshell.modules.revisorport import *
from devshell.modules.rpmcvspackage import *
from devshell.modules.sourceball import *
from devshell.modules.source import *
